config/routes.rb
PostitTemplate::Application.routes.draw do
  root 'posts#index'

  resources :posts, except: [:destroy] do
    resources :comments, only: [:create]
  end

  resources :categories
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :post_categories
  has_many :posts, through: :post_categories

  validates :name, presence: :true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  belongs_to :post

  validates :body, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories

  validates :title, presence: true, length: {minimum: 5}
  validates :description, presence: true
  validates :url, presence: true, uniqueness: true
end

app/models/post_category.rb
class PostCategory <ActiveRecord::Base
  belongs_to :post
  belongs_to :category

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new

  end

  def create
    @category = Category.new(caterory_params)

    if @category.save
      flash[:notice] = "Your post was created."
      redirect_to categories_path
    else
      flash[:notice] = @category.errors
      render 'new'
    end

  end

  def edit

  end

  def update
    if @category.update(caterory_params)
      flash[:notice] = "The category was updated"
      redirect_to categories_path
    else
      render :edit
    end
  end

  def destroy
    if @category.destroy
      flash[:notice] = "The category was deleted."
      redirect_to categories_path
    else
      flash[:notice] = "The category was not deleted."
      redirect_to categories_path
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
    
  end

  def caterory_params
    params.require(:category).permit!
    
  end




end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.creator = User.first #TODO

    if @comment.save
      flash[:notice] = 'Your comment was added.'
      redirect_to post_path(@post)
    else
      render 'posts/show'
    end    
  end

  private
  def comment_params
    params.require(:comment).permit!
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update]
  
  def index
    @posts = Post.all
  end

  def show
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.creator = User.first #TODO

    if @post.save
      flash[:notice] = "Your post was created."
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:notice] = "The post was updated"
      redirect_to posts_path
    else
      render :edit
    end
  end

  private
  def set_post
    @post = Post.find(params[:id])
    
  end
  def post_params
    params.require(:post).permit(:title, :url, :description, category_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def fix_url(str)
    str.starts_with?('http://') ? str : "http://#{str}"
  end

  def display_datetime(time)
    time.strftime("西元%Y年%m月%d日%H:%M:%S") #西元2015年04月04日14:27:08
  end
end

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %></span>

app/views/categories/_form.html.erb
<%= render 'shared/errors', object: @category %>

<div class="well">
  <%= form_for @category do |f| %>
    <div class="control-group">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <%= f.submit "Submit", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/categories/edit.html.erb
<%= render 'shared/content_title', title: 'Edit this category' %>

<%= render 'form' %>

app/views/categories/index.html.erb
<%= render 'shared/content_title', title: 'All Categories' %>
<ul>
<% @categories.each do |category| %>
  <li><%= category.name%>
<%= link_to "Edit",edit_category_path(category) %>
<%= link_to "Delete",category_path(category),method:"DELETE" %>
  </li>
<% end %>
</ul>
<%= link_to "New Category",new_category_path %>

app/views/categories/new.html.erb
<%= render 'shared/content_title', title: 'Create a category' %>
<%= render 'form' %>

app/views/categories/show.html.erb
<% header = link_to('All Posts', posts_path) + " &raquo; #{@category.name}".html_safe %>

<%= render 'shared/content_title', title: header %>

<% @category.posts.each do |post| %>
  <p>
    <%= render 'posts/post', post: post %>
  </p>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "Postit!", root_path, :class => 'brand' %>
  </li>
</ul>
<div class="nav_item">
  <%= link_to 'New Post', new_post_path, :class => 'btn btn-success btn-small'%>
</div>
<div class="btn-group nav-item">
  <%= link_to '#', class: "btn btn-small dropdown-toggle",'data-toggle' => 'dropdown' do %>
    Categories <span class='caret'></span>
  <% end %>
  <ul class="dropdown-menu">
    <% Category.all.each do |category| %>
    <li>
      <%= link_to category.name, category_path(category)%>
    </li>
    <% end %>
    <li class="divider"></li>
    <li>
      <%= link_to(new_category_path) do %>
        <i class="icon-plus"></i>
        New Category
      <% end %>
    </li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/posts/_form.html.erb
<%= render 'shared/errors', object: @post %>

<div class="well">
  <%= form_for @post do |f| %>
    <div class="control-group">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div class="control-group">
      <%= f.label :description %>
      <%= f.text_area :description, rows: 5 %>
    </div>
    <div class="control-group">
      <%= f.label :url %>
      <%= f.text_field :url %>
    </div>
    <div class="control-group">
      <%= f.label "Categories" %>
      <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
        <% cb.label(class: "checkbox inline") {cb.check_box(class: "checkbox") + cb.text} %>
      <% end %>
    </div>
    <%= f.submit(@post.new_record? ? 'Create Post' : 'Update Post', class: 'btn btn-primary') %>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div class="row">
  <div class="span8 well">
    <%= render post.categories %>
    <h4><%= link_to post.title, post_path(post) %></h4>
    <p><%= post.description %></p>
    <p>
      <span class="quiet">posted by </span><%= post.creator.username %>
      <small>at <%= display_datetime(post.created_at) %></small>
    </p>
    <small>
    <span>
      <%= link_to("#{post.comments.size} comments", post_path(post)) %>
    </span>
    </small>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render 'shared/content_title', title: 'Edit this post' %>

<%= render 'form' %>

app/views/posts/index.html.erb
<%= render 'shared/content_title', title: 'All Posts' %>

<% @posts.each do |post| %>
  <p>
    <%= render 'post', post: post %>
  </p>
<% end %>

app/views/posts/new.html.erb
<%= render 'shared/content_title', title: 'Create a post' %>
<%= render 'form' %>

app/views/posts/show.html.erb
<h4>Hi there, you're viewing <%= link_to @post.title, fix_url(@post.url) %></h4>

<p>
  <%= render @post.categories %>
</p>
      
<%= render 'shared/content_title', title: @post.title %>


<p>
  <%= @post.description %>
</p>


<%= link_to 'Edit the post', edit_post_path(@post), class: "btn btn-primary" %>
<hr />
<p>
  <%= form_for [@post, @comment] do |f| %>
    <%= render 'shared/errors', object: @comment %>
    <div class="control-group">
      <%= f.label :body, 'Leave a comment' %>
      <%= f.text_area :body, rows: 3, class: 'span4' %>
    </div>
    <%= f.submit('Create Comment', class: 'btn btn-primary') %>
  <% end %>
</p>
<hr />
<h5>Comments:</h5>
<p>
  <% @post.comments.each do |comment| %>
    <p><%= comment.body %></p>
    <p>
      <span class="quiet">commented by </span><%= comment.creator.username %>
      <small>at <%= display_datetime(comment.created_at) %></small>
    </p>
  <% end %>
</p>

app/views/shared/_content_title.html.erb
<p class='lead'>
  <%= title %>
  <hr />
</p>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class='row'>
    <div class='alert alert-error span8'>
      <h5>Please fix the following errors:</h5>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>